export const question3examples = [
  "Product examples: Shoes, Keychains, Widgets,",
  "Service examples: Shoe Cleaning Service, Custom Keychains, Widget Marketing etc.",
  "Subscription example: Monthly subscription of widgets, Software as a service, A combination of products and services",
];

export const question4a = [
  "(your city)",
  "(your state or region)",
  "(your country)",
  "(other countries)",
];

export const question8b = [
  "(It is better/faster/more efficient than the competitors' products)",
  "(People will have a better experience than they will get from the competitors' products)",
  "(Other people will want to watch or get involved because of the use of your product)",
  "(It makes or saves people money)",
];

export const question8bExamples = [
  "Example: A microwave functions faster than an oven for cooking meals.",
  "Example: a recliner chair provides a more relaxing sitting experience than sitting on a chair that doesn't recline.",
  "Example: Driving a luxury car makes other people perceive that you are making more money than driving an average car.",
  "Example: Bundling home and auto insurance with the same company saves money",
];

export const set1 : string[] =[
    'Advisory and Financial Services',
    'Technology',
    'Online Retail',
    'Specialist Engineering, Infrastructure and Contractors',
    'Consumer Goods and Services',
    'Industrial Machinery, Gas and Chemicals',
    'Life Sciences',
    'Accommodation and Food Services',
    'Administration, Business Support and Waste Management Services',
    'Educational Services',
    'Arts, Entertainment and Recreation',
    'Wholesale Trade',
    'Retail Trade',
    'Healthcare and Social Assistance',
    'Transportation and Warehousing',
    'Construction',
    'Professional, Scientific and Technical Services',
    'Manufacturing'
]

export type Services_list = {
  [key: string]: string[];
};

export const services_list: Services_list = {
  'productValue': [
    "Functional value ",
    "Experiential value ",
    "Social Value ",
    "Economic value "],

  'productSaleRegion': ['Local','Regional','National','Global'],

  'productType' : ['Product', 'Service','Subscription'],

  'knowSegment': ['Yes', 'No'],

  'Advisory and Financial Services':[
    'AD&D Insurance', 'Agricultural Banks', 'Agricultural Insurance', 'Aircraft Rental Services', 
    'Airline Catering Services', 'Armored Transportation Services', 'Audio & Visual Equipment Rental',
    'Audit Services', 'Auto Extended Warranty Providers', 'Automobile Insurance', 
    'Background Check Services', 'Bankruptcy Lawyers & Attorneys', 'Batting Cages', 
    'Benefit Administration Services', 'Boat Rentals', 'Bond Management', 'Business Brokers', 
    'Business Concierge Services', 'Business Financing', 'Business Information Resellers', 
    'Business Insurance', 'Business Lawyers & Attorneys', 'Business Process Outsourcing Services', 
    'Business Valuation Firms', 'Card Reward Program Services', 'Casting Agencies', 
    'Check Cashing & Payday Loan Services', 'Child Adoption Agencies', 'Claims Adjusting', 
    'Commercial Aircraft Leasing', 'Commercial Auto Insurance', 'Commercial Construction Insurance', 
    'Company Research Services', 'Construction Machinery Rentals', 'Consumer Lawyers & Attorneys', 
    'Contractors\' Insurance', 'Corporate Law Firms', 'Credit Repair Services', 
    'Criminal Lawyers & Attorneys', 'Cryptocurrency Exchanges', 'Customer Care Centers', 
    'Customs Brokers', 'Cyber Liability Insurance', 'Data Center Colocation Services', 
    'Debt Relief Services', 'Dental Insurance', 'Disability Insurance', 
    'Distribution and Logistics Consulting Services', 'Document Management Services', 
    'eDiscovery Consulting Services', 'eDiscovery Software Publishing', 'eTrading Software Developers', 
    'Education Consultants', 'Employee Assistance Program Services', 'Employee Relocation Services', 
    'Employment Law Firms', 'Energy & Utility Consulting Services', 'Entertainment Insurance', 
    'Entertainment Lawyers & Attorneys', 'Estate Lawyers & Attorneys', 'Estate Liquidation Services', 
    'Executive Search Recruiters', 'Expert Networks', 'Expert Witness Consulting Services', 
    'Family Law & Divorce Lawyers & Attorneys', 'Financial Data Service Providers', 'Fleet Car Leasing', 
    'Foreclosure Lawyers & Attorneys', 'Foreign Currency Exchange Services', 'Forensic Accounting Services', 
    'Franchise Resale Brokers & Consultants', 'Group Purchasing Organizations', 'Health & Medical Reinsurance', 
    'Healthcare Consultants', 'Healthcare Lawyers & Attorneys', 'Hedge Funds', 'High Frequency Trading', 
    'HMO Providers', 'Home Furniture Rental', 'Home Medical Equipment Rentals', 'Home Warranty Providers', 
    'Homeowners\' Insurance', 'Identity Theft Insurance', 'Immigration Lawyers & Attorneys', 
    'Installment Lenders', 'Insurance Claims Processing Software', 'Insurance Lawyers & Attorneys', 
    'Intermodal Container Leasing', 'International Law Firms', 'International Trade Financing', 
    'Invoice Factoring', 'Jet Ski Rental', 'Kayak Rental', 'Labor Relations Lawyers & Attorneys', 
    'Libraries & Archives', 'Long Term Care Insurance', 'Marketing Consultants', 'Mediation Services', 
    'Medical Billing Services', 'Medical Claims Processing Services', 'Medical Equipment Rental', 
    'Medical Group Practice Management', 'Medical Malpractice Insurance', 'Medical Patient Financing', 
    'Merchant Banking Services', 'Model Agencies', 'Money Transferring Services', 
    'Motion Picture & Theatrical Equipment Rental', 'Mutual Fund Management', 
    'Nondestructive Testing Services', 'Office Furniture Rental', 'Oil, Gas & Mining Consultants', 'Online Insurance Brokers',  
    'Online Legal Services',  'Online Mortgage Brokers',  'Online Payment Processors',  'Online Stock Brokerages',  
    'Pallet & Skid Rental',  'Party Bus Rentals',  'Pawn Shops',  'PeertoPeer Lending Platforms',  'Pension Fund Management',  
    'Personal Finance & Money Management Software Developers',  'Personal Injury Lawyers & Attorneys',  
    'Pharmaceutical Contract Management Consulting',  'Pharmaceuticals Packing & Labeling Services',  'Portable Toilet Rental',
    'Prepaid Credit & Debit Card Providers',  'Private Banking Services',  'Product Returns Management Services',  
    'Product Warranty Insurance',  'Professional Organizations',  'Property & Casualty Reinsurance',  'Public Opinion Research',
    'Railroad Car Rental & Leasing',  'Real Estate Law Firms',  'Regional Banks',  "Renters' Insurance",  'Repossession Services',
    'Reverse Mortgages Providers',  'Risk Management, Insurance Advisory & Consulting',  'RV & Camper Van Rental',  
    'Serviced Office Leasing',  'Settlement Funding Companies',  'Shared Office Spaces',  'Stenographic Services',  
    'Stock Price & Rating Research',  'Subprime Auto Loans',  'Supply Chain Management Services',  'Tax Lawyers and Attorneys',
    'ThirdParty Data Entry Services',  'ThirdParty Logistics',  'Title Insurance',  'Trademark & Patent Lawyers & Attorneys',
    'Transcription Services',  'Travel Insurance',  'Trial Consultants',  'Typing Services',  'Vision Insurance',  
    'Weather Forecasting Services',  'Workers\' Compensation Insurance'],

  'Technology':[
    '3D Printer Manufacturing', '3D Printing & Rapid Prototyping Services', 
    'Activated Carbon Manufacturing', 'Adult & Pornographic Websites', 'Air Purification Equipment Manufacturing', 
    'ATM Manufacturing', 'Audio and Visual Equipment Repair Services', 'Augmented Reality Software', 
    'Bare Printed Circuit Board Manufacturing', 'Battery Recycling', 'Binoculars Manufacturing', 'Biomass Power', 
    'Biometrics Scan Software', 'Bioplastics Manufacturing', 'Building Lighting Control System Manufacturing', 
    'Business Intelligence Software', 'CAD Software Developers', 'Capacitor Manufacturing', 'Cell Phone Recycling', 
    'Chatbot Software', 'Cloud Security Software', 'Collaboration & Project Management Software', 'Colocation Facilities', 
    'ComputerAided Design Software Developers', 'Conferencing Service Providers', 'Consumer Drone Manufacturing', 
    'Contact Tracing Systems', 'Contactless Payment Systems', 'Cooking Oil Recycling', 'Court Reporting Services',
    'CRM System Providers', 'Cryotherapy', 'Dark Fiber Network Operators', 'Data Backup Software', 'Data Loss Prevention Software',
    'Data Recovery Services', 'Digital Advertising Agencies', 'Digital Forensic Services', 'Document Digitization Services', 
    'EBook Publishing', 'Ecigarette Manufacturing', 'Educational Software', 'Electric Vehicle Charging Stations', 
    'Electricity & Signal Testing Instrument Manufacturing', 'Electronic Access Control System Manufacturing', 
    'Electronic Article Surveillance Product Manufacturing', 'Electronic Design Automation Software Developers', 
    'Electronic Goods Recycling', 'Endpoint Security Software', 'Enterprise Resource Planning Software Developers', 
    'Ethanol Fuel Production', 'ETL & ELT Data Management Software', 'Facial Recognition Software', 'Fantasy Sports Services',
    'FiberOptic Cable Manufacturing', 'Field Service Management Software', 'Film Animation Services', 'Fire & Smoke Alarm Manufacturing',
    'Fleet Telematics Systems', 'Flyboarding Equipment Manufacturing', 'Fraud Detection Software Developers', 
    'Gas Detection Device Manufacturing', 'Geothermal Electricity Plant Operation', 'Headphone Manufacturing', 
    'Home Automation Services', 'HR & Payroll Software', 'Hybrid & Electric Vehicle Manufacturing', 'Identity Management Software', 
    'Identity Theft Protection Services', 'Internet Hosting Services', 'Internet Radio Broadcasting', 'IT Security Consulting',
    'Language Learning Software Developers', 'Learning Management Software', 'LED Manufacturing', 'Lithium Battery Manufacturing',
    'Metal Detector Manufacturing', 'Microprocessor Chip Manufacturing', 'Microscope Manufacturing', 'Music Streaming Services',
    'Night Vision Equipment Manufacturing', 'Nonferrous Metal Recycling', 'Online Payment Processing Software Developers', 
    'Online Recruitment Sites', 'Online Survey Software', 'Optical Character Recognition Software', 
    'Optical CharacterRecognition Software Developers', 'Ordnance Manufacturing', 'Oscilloscope Manufacturing', 
    'Point of Sale Software Developers', 'Power Circuit Breaker Manufacturing', 'Precision Agriculture Systems & Services',
    'Pressure Sensor Manufacturing', 'RealTime Traffic Information Providers', 'Respiratory Protection Equipment Manufacturing',
    'Safe & Vault Manufacturing', 'Scale & Balance Manufacturing', 'Scrap Metal Recycling',
    'SeismicMonitoring Equipment Manufacturing', 'SEO & Internet Marketing Consultants', 'Smart Lighting Manufacturing', 
    'Smart Meter Manufacturing', 'Smart Speaker Manufacturing', 'Smart Thermostat Manufacturing', 'Smartphone App Developers', 
    'Social Network Game Development', 'Social Networking Sites', 'Software Testing Services', 'Solar Farm Developers', 
    'Solar Panel Installation', 'Sonar Device Manufacturing', 'Speech & Voice Recognition Software Developers', 
    'Storage Area Network Software Development', 'Tax Preparation Software Developers', 'Thermostat Manufacturing', 
    'Tire & Rubber Recycling', 'Traffic Light Manufacturing', 'Ultrasonic Cleaning Equipment Manufacturing', 'Urinal Manufacturing', 
    'Variable Message Signage Manufacturing', 'Video Conferencing Software Developers', 'Video Games Software Developers', 
    'Video Games Software Publishing',"Video Management Platform Software","Virtual Data Rooms","Virtual Reality Software",
    "WastetoEnergy Plant Operation","Wearable Device Manufacturing","Web Design Services","Web Domain Name Sales",
    "Website Creation Software Developers","Wind Turbine Installation","Wire Connector Manufacturing",
    "Wireless Internet Service Providers in the US"],

  'Online Retail': [
    "Daily Deals Sites","Digital Music Downloads","Online Air Travel Bookings","Online Antiques & Collectibles Sales",
    "Online Apartment Rental Services","Online Art Sales","Online Audio Equipment Sales","Online Automotive Parts & Accessories Sales",
    "Online Baby & Infant Apparel Sales","Online Baby Product Sales","Online Beer, Wine & Liquor Sales","Online Book Sales",
    "Online Camera & Camcorder Sales","Online Car Dealers","Online Car Rental","Online CD, DVD & DVR Sales",
    "Online Children's Toy Sales","Online Computer & Tablet Sales","Online Computer Software Sales","Online Designer Clothing Sales",
    "Online Electrical Office Equipment Sales","Online Event Ticket Sales","Online Eyeglasses & Contact Lens Sales",
    "Online Flower Shops","Online Gift Vouchers","Online Greeting Card Sales","Online Grocery Sales","Online Gun & Ammunition Sales",
    "Online Handbag & Luggage Sales","Online Hardware & Tool Sales","Online Hobby & Craft Supplies Sales","Online Home Furnishing Sales",
    "Online Hotel Booking","Online Household Furniture Sales","Online Industrial Machinery & Equipment Sales",
    "Online Industrial Supplies Sales","Online Jewelry & Watch Sales","Online Kitchenware Sales","Online Large Kitchen Appliance Sales",
    "Online Medical Supplies Sales","Online Men's Clothing Sales","Online Music Instrument Sales","Online Office & School Supply Sales",
    "Online Office Furniture Sales","Online Original Design TShirt Sales","Online Paint Sales","Online Perfume & Cosmetic Sales",
    "Online Pet Food & Pet Supply Sales","Online Pharmaceutical Sales","Online Photo Printing","Online Plumbing & Electrical Supply Sales",
    "Online Residential Home Sale Listings","Online Scenic & Sightseeing Tour Bookings","Online Sea Travel Bookings","Online Shoe Sales",
    "Online Small Electrical Appliance Sales","Online Sporting Apparel Sales","Online Sporting Goods Sales","Online Sunglasses Sales",
    "Online Television Sales","Online Tour Arrangement Bookings","Online Tutoring Services","Online Video Downloads",
    "Online Video Game Console Sales","Online Video Game Sales","Online Vitamin & Supplement Sales","Online Weight Loss Services",
    "Online Women's Clothing Sales","Video Streaming Services"]
,
  'Specialist Engineering, Infrastructure and Contractors': [
    "Aerospace Engineering Services","Agricultural Engineering Services","Airport Management Services","Airport Terminal Construction",
    "Artificial Grass Turf Installation","Bridge & Structure Painting Contractors","Building Exterior Cleaners",
    "Cell Site Operation and Leasing","Cementing Oil & Gas Well Services","Commercial Property Remodeling",
    "Commercial Shelving Manufacturing","Communication Antenna Construction","Computer Facilities Management Services",
    "Concrete Pipe Manufacturing","Concrete Reinforcing Bar Manufacturing","Construction Project Management Services",
    "Corrosion Protection Engineering Services","Damage Restoration Services","Deck & Patio Construction",
    "Demolition Equipment Manufacturing","Dog Park Design Services","Dredging Services","Dump Truck Services","Dumpster Rental",
    "Editorial Services","Electric Transmission Line & Tower Installation","Elevator Manufacturing","Engineered Wood Product Manufacturing",
    "Escalator Installation & Maintenance","Escalator Manufacturing","Fence & Scaffolding Manufacturing","Fence & Scaffolding Rental",
    "General Freight Trucking (Less Than Truckload)","General Freight Trucking (Truckload)","Hazardous Waste Collection",
    "Heavy-Duty OTR Tire Manufacturing","Hoist & Winch Manufacturing","Hospital Construction","Hotel Construction",
    "House Painting & Decorating Contractors","Hydraulic Fracturing Services","Hydroelectric Power Plant Construction",
    "Indoor Sports Facilities Management","Industrial Design Services","Industrial Engineering Services","Insulation Contractors",
    "Laboratory Design & Build Contractors","Local Refrigerated Trucking","Long-Distance Refrigerated Trucking","Lumber Yards",
    "Marine Salvage Services","Metal Door Manufacturing","Monument Makers","Natural Gas Liquid Processing",
    "Nonresidential Property Managers","Nuclear Power Plant Construction","Offshore Drilling Extraction",
    "Offshore Oil Rig & Platform Construction","Oil and Gas Drilling Equipment Manufacturing","Oil Field Drilling Services",
    "Ornamental & Architectural Metalwork Manufacturing","Overhead Crane Manufacturing","Playground Design Services","Potash Mining",
    "Powder Coating Services","Railroad Track Construction","Reconstituted Wood Product Manufacturing","Residential Property Managers",
    "Restaurant Construction","Retail Store Fixture Dealers","Sandblasting Services","Scaffolding Contractors",
    "Septic, Drain & Sewer Cleaning Services","Sewer & Pipeline Rehabilitation","Sheet Metal Work Manufacturing",
    "Sheet Metal Roofing Manufacturing","Shopping Mall Management","Shortline Railroad Operation","Snowplowing Services",
    "Soil Testing Services","Solar Water Heater Installation","Sports & Athletic Field Construction","Sports Stadium Construction",
    "Street Cleaning Services","Stringed Instrument Manufacturing","Toll Road Operation","Tunnel Construction","Urban Planning Software",
    "Wallpapering Services","Water & Air Quality Testing Services","Water Well Drilling Services","Wind Farm Construction",
    "Window Coverings Wholesaling","Window Installation","Window Washing","Wireless Tower Construction","Wood Chip Manufacturing",
    "Wood Door & Window Manufacturing","Wood Flooring Manufacturing in the US"]
,
  'Consumer Goods and Services': [
    'Acoustic & Electric Guitar','Manufacturing','Acupuncture Schools','Adhesive Tape Manufacturing','Adjustable Bed & Mattress Manufacturing',
    'Adult Stores','Aerial Yoga Classes','Aestheticians','AfterSchool Program Providers','Air Duct Cleaning Services','Air Gun & Airsoft Gun Manufacturing',
    'Airport Shuttle Operators','Aluminum Foil Manufacturing','Anesthesiologists','Animal Control Services','Animal Physical Therapists',
    'Animal Rescue Shelters','AnimalAssisted Therapy','Antique Stores','Archery Ranges','Art Classes','Art Consulting','Art Galleries','Art Installation Services',
    'Art Restoration Services','Art Space Rental','Art Supply Stores','Athleisure Clothing Manufacturing','Athletic Event Organizers','Athletic Shoe Stores',
    'ATV Manufacturing','ATV Rentals & Tour Services','Auction Houses','Audiobook Publishing','Auto Electrical Services','Auto Windshield Repair Services','Baby Food Manufacturing',
    'Backpack & Courier Bag Manufacturing','Bacon Production','Bagel Stores','Bail Bond Services','Bakery Cafes','Ballet Schools','Barbecue & Grill Manufacturing','Barber Shops',
    'Barre Classes','Bartending Schools','BBQ & Outdoor Cooking Stores','BBQ Charcoal Manufacturing','BBQ Sauce Production','Beach Equipment Rental','Beauty Supply Stores',
    'Bed & Mattress Stores',
    'Bicycle Manufacturing',
    'Bike Rental',
    'Bike Tours',
    'Bird Shops',
    'Bleach Manufacturing',
    'Board Game Manufacturing',
    'Boat Part Suppliers',
    'Body Armor Manufacturing',
    'Body Contouring',
    'Body Piercing Studios',
    'Boutique Hotels',
    'Boxing Gyms & Clubs',
    'Boxing Promoters',
    'Breakfast Restaurants & Diners',
    'Brewery Tours',
    'Brewpubs',
    'Bridal Stores',
    'Budget Airlines','Buffet Restaurants',
    'Bungee Jumping Tours',
    'Burger Restaurants',
    'Bus Rental',
    'Cabinet Makers',
    'Cable Shopping Networks',
    'Calligraphy Services',
    'Candle Manufacturing',
    'Cannabis Equipment & Accessory Stores',
    'Car Sharing Providers',
    'Cardio Classes',
    'Carpet Dyeing Services',
    'Cell Phone Repair',
    'Charcoal Grilling Equipment Stores',
    'Charter Schools',
    'Cheese Production',
    "Children's Book Publishing",
    'Chinese Restaurants',
    'Chocolate Stores',
    'Cider Production',
    'Cideries',
    'Cigar Lounges',
    'Classic Car Dealers',
    'Clock Repair Services',
    'Clothing & Apparel Rental',
    'Clothing Alteration Services',
    'Clothing Boutiques',
    'Cocktail Bars',
    'Cocoa & Drinking Chocolate Production',
    'Coffee Creamer Production',
    'Comedy Clubs',
    'Comic Book Publishing',
    'Commercial Cleaning & Sanitation Services',
    'Commercial Embroidery Services',
    'Commercial Window Cleaning Services',
    'Computer Rental',
    'Cookie & Wafer Manufacturing',
    'Cookie Shops',
    'Cooking Classes',
    'Cosmetology & Beauty Schools',
    'Cotton PersonalCare Product Manufacturing',
    'Countertop Manufacturing',
    'Cracker & Biscuits Manufacturing',
    'Craft Beer Production',
    'Craft Spirits Production',
    'Cruise Line Operators',
    'Culinary Arts Schools',
    'Cupcake Stores',
    'Cured Meat Production',
    'Curtain & Drape Manufacturing',
    'Custom Cake Services',
    'Custom Screen Printing',
    'Dance Schools',
    'Dance Studios',
    'Dancewear Stores',
    'Day Camps',
    'Delicatessens',
    'Dental Schools',
    'Deodorant Manufacturing',
    'Dessert Stores',
    'Diaper Manufacturing',
    'Discount Department Stores',
    'Dishwasher Manufacturing',
    'DoItYourself Auto Shops',
    'Dog & Pet Breeders',
    'Dog Training Services',
    'Dog Walking Services',
    'Door Installation & Repair Services',
    'Door Lock & Lockset Manufacturing',
    'Doughnut Stores',
    'Dried Fruit & Vegetable Snack Production',
    'Driving Schools',
    'Dry Pasta Production',
    'Dry Pet Food Production',
    'Durable Baby Goods Stores',
    'DutyFree Shops',
    'Early Childhood Learning Centers',
    'Electric Scooter Rental',
    'Electronic Cigarette & Vape Shops',
    'Engraving Services',
    'Escape Rooms',
    'Escort Services',
    'Ethnic Supermarkets',
    'Event Photography',
    'Exercise Equipment Stores',
    'Extended Stay Hotels',
    'External Sliding Door Manufacturing',
    'Eyebrow Services',
    'Eyeglasses Frames Manufacturing',
    'Farm Equipment Repair',
    'Farm Supply Stores',
    'Farmers Markets',
    'Faucet Manufacturing',
    'Fine Dining Restaurants',
    'Fire Protection and Security System Installation Contractors',
    'Fire Protection Consultants',
    'Firearm Training',
    'Fireplace Services',
    'Fireworks Retailers',
    'Fishing Boat Charter',
    'Flag Manufacturing',
    'Flea Markets',
    'Flight Instructors',
    'Flying Schools',
    'Food Courts & Halls',
    'Food Delivery Services',
    'Food Processor & Blender Manufacturing',
    'Food Safety Training',
    'Food Trucks',
    'French Restaurants',
    'Fresh Bread & Bakery Goods Wholesaling',
    'Frozen Cake & Pastry Manufacturing',
    'Frozen Dough & Batter Production',
    'Frozen Fruit & Juice Production',
    'Frozen Pizza Production',
    'Frozen Potato Product Production',
    'Frozen Vegetable Production',
    'Frozen Yogurt Stores',
    'Furniture Restoration Services',
    'Garage Door Installation',
    'Garage Door Manufacturing',
    'Generator Rental',
    'Ghost Kitchens',
    'Glass Stores',
    'GoKart Racing Tracks',
    'Golf Cart Dealers',
    'Golf Cart Manufacturing',
    'Golf Cart Rentals',
    'Golf Equipment Stores',
    'Golf Instructors',
    'Golf Resorts',
    'Greek Restaurants',
    'Grocery Delivery Services',
    'Grouting Contractors',
    'Guitar Stores',
    'Gum Production',
    'Gun & Ammunition Stores',
    'Gutter Services',
    'Gymnastics Classes',
    'Hair Cleaning Product Manufacturing',
    'Hair Color Product Manufacturing',
    'Hair Extension Services',
    'Hair Removal Services',
    'Hair Remover Product Manufacturing',
    'Hair Salons',
    'Hand Sanitizer Manufacturing',
    'Hang Glider Sightseeing',
    'Hard Seltzer Production',
    'Hat & Cap Stores',
    'Health Retreats',
    'Hearing Aid Stores',
    'High Fructose Corn Syrup Production',
    'Hiking & Outdoor Equipment Stores',
    'Hookah Lounges',
    'Hops Farming',
    'Horse Racing Tracks',
    'Horse Rentals',
    'Horse Training Services',
    'Horseback Tours',
    'Hospitality Management Schools',
    'Hostels',
    'Hot Dog & Hamburger Bun Production',
    'Hot Dog & Sausage Production',
    'Hot Sauce Production',
    'Hot Tub Manufacturing',
    'Household Appliance Stores',
    'Hunting & Fishing Supplies Stores',
    'Hydroponic Growing Equipment Stores',
    'Ice Cream Stores',
    'Ice Delivery Services',
    'Ice Manufacturing',
    'Ice Rinks',
    'Indian Restaurants',
    'Indoor Climbing Walls',
    'Indoor Cycling Workout Classes',
    'Indoor Marble Contractors',
    'Indoor Play Centers',
    'Industrial Chocolate Production',
    'Infant Formula Manufacturing',
    'Interval Training Gyms',
    'Investigation Services',
    'Italian Restaurants',
    'Japanese Restaurants',
    'Jazz Clubs & Lounges',
    'Jewelry Designers',
    'Jewelry Wholesaling',
    'Juice & Smoothie Bars','Karaoke Bars',
    'Karaoke Machine Rental',
    'Karate Studios',
    'Key Duplication Services',
    'Kickboxing Studios',
    'Kitchen & Cookware Stores',
    'Kombucha Production',
    'Korean Restaurants',
    'Lamp & Lighting Stores',
    'LAN Gaming Centers',
    'Language Schools',
    'Laser Tag Arenas',
    'Lawn Mower Rentals',
    'Lawn Sprinkler Installation Contractors',
    'Leather Boot Manufacturing',
    'Leather Cleaning & Repair Services',
    'Licensed Sports Apparel Stores',
    'Limousine & Town Car Services',
    'Lingerie Manufacturing',
    'Lingerie Stores',
    'Lip Care Product Manufacturing',
    'Lipstick Manufacturing',
    'Live Performance Theaters',
    'Locksmiths',
    'Luggage & Leather Goods Stores',
    'Magazine & Newspaper Stands',
    'Magicians',
    'Major Smart Appliance Manufacturing',
    'Makerspace Design Services',
    'Makeup Artists',
    'Mall Carts & Kiosks',
    'Marine Engineering Services',
    'Martial Arts Studios',
    'Massage Schools',
    'Massage Services',
    'Maternity Wear Stores',
    'Mayonnaise Production',
    'Meal Kit Delivery Services',
    'Meal Replacement Product Manufacturing',
    'Meat Alternatives Production',
    'Meat Jerky Production',
    'Meditation Studios',
    'Mediterranean Restaurants',
    'Mexican Restaurants',
    'Microwave Oven Manufacturing',
    'Middle Eastern Restaurants',
    'Miniature Golf Courses',
    'Mixed Martial Arts Studios',
    'Mobile Home Manufacturing',
    'Mobile Storage Services',
    'Motorcycle Rental',
    'Mouthwash Manufacturing',
    'Movie Rental Kiosks',
    'Musical Instrument Rental Services',
    'Musical Instrument Repair Services',
    'Nail Polish Manufacturing',
    'Newswire Services',
    'Nightclubs',
    'Noodle Restaurants',
    'Nursery Schools',
    'Nursing Schools',
    'Office Cleaning Services',
    'Office Equipment Repair Services',
    'Office Equipment Stores',
    'Office Furniture Stores',
    'Office Plant Services',
    'Officiant Services',
    'Olive Oil Production',
    'Online Gambling Services',
    'Online Used Book Sales',
    'Organic Grocery Stores',
    'Organic Snack Production',
    'Outdoor Furniture Manufacturing',
    'Outdoor Marble Contractors',
    'Outdoor Movie Operators',
    'Outlet Stores',
    'Oven & Stove Manufacturing',
    'Paddleboarding Lessons',
    'Paint & Sip Studios',
    'PaintYourOwn Pottery Studios',
    'Paintball Fields',
    'Pancake Restaurants',
    'Paper Cup Manufacturing',
    'Paper Towel Manufacturing',
    'Paperboard Drinking Cup Manufacturing',
    'Parachute Manufacturing',
    'Parasail Tours',
    'Party & Event Planners',
    'Party Supply Rental',
    'Pasta Sauce Production',
    'Patio Coverings',
    'Patisseries and Cake Shops',
    'Peanut Butter Production',
    'Perfume & Fragrance Manufacturing',
    'Perfume & Fragrance Stores',
    'Personal Chef Services',
    'Personal Protective Equipment Manufacturing',
    'Personal Waxing & Nail Salons',
    'Pet Adoption Services',
    'Pet Cremation Services',
    'Pet Food & Supplies Wholesaling',
    'Pet Food Production',
    'Pet Hospice',
    'Pet Insurance',
    'Pet Photography Services',
    'Pet Sitting Services',
    'Pet Training Services',
    'Pet Transportation Services',
    'Pet Waste Products',
    'Petting Zoos & Tourist Farms',
    'Petting Zoos',
    'Photo Booth Rental',
    'Photo Restoration Services',
    'Photography Schools',
    'Piano Repair & Tuning Services',
    'Piano Stores',
    'Picture Framing Stores',
    'Pizza Restaurants',
    'Playground & Park Equipment Manufacturing',
    "PlusSize Men's Clothing Stores",
    "PlusSize Women's Clothing Stores",
    'Poke Shops',
    'Pool & Billiard Halls',
    'Popcorn Production',
    'Potato Chip Production',
    'Potato Farming',
    'PreMade Salsa Production',
    'Premium Pet Food Production',
    'Premium Steak Restaurants',
    'Prepared Frozen Fish Production',
    'Prepared Soups Production',
    'Pressure Washing Services',
    'Pretzel Stores',
    'Private Boat Charters',
    'Private Detective Services',
    'Private Jet Charters',
    'Private Music Classes',
    'Protective Sports Equipment Manufacturing',
    'Psychic Services'],
  
  'Industrial Machinery, Gas and Chemicals': [
    "Acetylene Production",
    "Aerial Work Platform Manufacturing",
    "Agricultural Machinery Wholesaling",
    "Air & Gas Compressor Manufacturing",
    "Aircraft Parts Distributors",
    "Ambulance Manufacturing",
    "Architectural, Flat & Plate Glass Distributors",
    "Argon & Hydrogen Manufacturing",
    "Armored Vehicle Manufacturing",
    "Audio & Video Equipment Distributors",
    "Auto Air Conditioning Manufacturing",
    "Auto Exhaust System Manufacturing",
    "Auto Lighting Equipment Manufacturing",
    "Auto Parts Remanufacturing",
    "Auto Transmission Manufacturing",
    "Automated Guided Vehicle Manufacturing",
    "Automatic Fire Sprinkler System Manufacturing",
    "Automotive Coatings Manufacturing",
    "Automotive Glass Manufacturing",
    "Autonomous Underwater Vehicle Manufacturing",
    "Axle & Transaxle Manufacturing",
    "Blow Molding Machinery Manufacturing",
    "Brewery Equipment Wholesalers",
    "Car Airbag Manufacturing",
    "Car Wheel Manufacturing",
    "Carbon Dioxide Production",
    "Carbon Fiber & Graphene Manufacturing",
    "Carburetor Manufacturing",
    "Carpet & Floor Covering Distributors",
    "Catalog & Directory Printing",
    "Catalytic Converter Manufacturing",
    "Chipping & Grinding Equipment Manufacturing",
    "Chlorine Manufacturing",
    "Cleaning & Maintenance Supplies Distributors",
    "Combine Harvester Manufacturing",
    "Commercial Cooking Equipment Manufacturing",
    "Commercial Dishwasher Manufacturing",
    "Commercial Oven Manufacturing",
    "Commercial Refrigerator Manufacturing",
    "Commercial Washing Machine Manufacturing",
    "Contract Injection Molding Manufacturing",
    "Conveying Equipment Manufacturing",
    "Crane Rental Services",
    "Cutting Tool & Machine Tool Accessory Manufacturing",
    "Diesel Engine & Parts Wholesaling",
    "Digital Printing",
    "Disinfectant Manufacturing",
    "Electric Submersible Pump Manufacturing",
    "Engine Filter Manufacturing",
    "Engine Radiator Manufacturing",
    "Engine Rebuilding & Remanufacturing",
    "Essential Oil Manufacturing",
    "Fabricated Structural Metal Manufacturing",
    "Fire Extinguisher Manufacturing",
    "Fire Truck Manufacturing",
    "Fluid Power Equipment Distributors",
    "Food Processing Equipment Distributors",
    "Forklift Manufacturing",
    "Gasket & Seal Manufacturing",
    "Gear & Speed Changer Manufacturing",
    "Hand Tool Manufacturing",
    "Heavy Duty Truck Parts Dealers",
    "Heavy-Duty Diesel Engine Manufacturing",
    "Helicopter Manufacturing",
    "Helium Production",
    "Hydraulic & Pneumatic Jack Manufacturing",
    "Hydraulic Motor Manufacturing",
    "Ice Making Machine Manufacturing",
    "Industrial & Commercial Fan & Blower Manufacturing",
    "Industrial & Fluid Power Valve Manufacturing",
    "Industrial Spraying Equipment Manufacturing",
    "Lawn and Garden Equipment Manufacturing",
    "Lead Smelting & Refining",
    "Machine Tool Distributors",
    "Material Handling Equipment Distributors",
    "Metal Barrel & Drum Manufacturing",
    "Methanol Production",
    "Mixer & Paver Manufacturing",
    "Motor Grader Manufacturing",
    "Motor Oil Manufacturing",
    "Newsprint Manufacturing",
    "Office Fixture and Storage Manufacturing",
    "Packaging Machinery Manufacturing",
    "Paint Remover Manufacturing",
    "Personal Watercraft Manufacturing",
    "Photographic & Photocopying Equipment Manufacturing",
    "Piano Manufacturing",
    "Power Tool Manufacturing",
    "Precious Metal Dealers",
    "Prime Mover Generator Sets Manufacturing",
    "Printing Equipment Distributors",
    "Propane Tank Exchange Services",
    "PTFE (Teflon) Coating Manufacturing",
    "Railcar Manufacturing",
    "Recreational Vehicle Manufacturing",
    "Safety Equipment & Supplies Distributors",
    "School Supplies Wholesaling",
    "Shipping Container Manufacturing",
    "Silicone Manufacturing",
    "Snow Mobile Manufacturing",
    "Snowplow Manufacturing",
    "Spark Plug Manufacturing",
    "Stair Contractors",
    "Stall Installation Services",
    "Steel Wire Drawing",
    "Submarine Manufacturing",
    "Sulfur & Sulfuric Acid Manufacturing",
    "Synthetic Organic Alcohol Manufacturing",
    "Titanium Dioxide Manufacturing",
    "Titanium Manufacturing",
    "Tractor Shovel Loader Manufacturing",
    "Trailer & Camper Manufacturing",
    "Transformer Oil Production",
    "Truck Repair",
    "Truck Trailer Dealers",
    "Truck Trailer Manufacturing",
    "TruckMounted Cement Mixer Manufacturing",
    "TruckMounted Crane Manufacturing",
    "Turbocharger Manufacturing",
    "Unmanned Aerial Vehicle (UAV) Manufacturing",
    "Used Aircraft & Equipment Dealers",
    "Used Truck Dealers",
    "Veterinarians' Equipment & Supplies Wholesaling",
    "Walkin & Cabinet Cooler Manufacturing",
    "Washer & Dryer Repair Services",
    "Water Heater Manufacturing",
    "Welding Equipment Distributors in the US"],

  'Life Sciences': [
    "Acne Treatment Manufacturing OTC",
    "Acupuncturists",
    "Addiction Medication Manufacturing",
    "ADHD Medication Manufacturing",
    "Adult Day Care",
    "Adult Diaper Manufacturing",
    "Air Ambulance Services",
    "Allergists",
    "Allergy Medicine Manufacturing OTC",
    "Ambulatory Surgery Centers",
    "Animal Health Biotechnology",
    "Animal Pharmaceuticals",
    "AntiFungal Medication OTC",
    "Antibiotic Manufacturing",
    "Antidepressant Manufacturing",
    "Antiseptic Manufacturing",
    "Antiviral Drug Manufacturing",
    "Artificial Joint & Limb Manufacturing",
    "Assisted Living Facilities",
    "Asthma & COPD Medicine Manufacturing",
    "Athlete's Foot Treatment Manufacturing OTC",
    "Audiologists",
    "Behavioral Therapists",
    "Blood Banking & Tissue Typing Facilities",
    "Blood Testing Services",
    "Cardiologists",
    "CBD Product Manufacturing",
    "Cell Therapy",
    "Children's Specialty Hospitals",
    "Clinical Trial Data Management Services",
    "Clinical Trial Support Services",
    "Coffin & Casket Manufacturing",
    "Cold Sore Medication Manufacturing",
    "Compounding Pharmacies",
    "Contact Lens Manufacturing",
    "Contraceptive Tablet Manufacturing",
    "Contract Pharmaceutical Research Services",
    "Contract Research Organizations",
    "Corporate Wellness Services",
    "Cosmetic Dentists",
    "Cough & Cold Medicine Manufacturing OTC",
    "Cremation Services",
    "Cryogenic Biobanking Services",
    "Decongestant Manufacturing OTC",
    "Defibrillator Manufacturing",
    "Dental Clinical Instrument Manufacturing",
    "Dental Equipment Dealers",
    "Dental Laboratories",
    "Dermatologists",
    "Diagnostic Imaging Centers",
    "Dialysis Centers",
    "Dialysis Equipment Manufacturing",
    "DNA & DNA Forensic Laboratories",
    "Drug & Alcohol Rehabilitation Clinics",
    "Drug & Alcohol Test Kit Manufacturing",
    "Ear Care Medication Manufacturing OTC",
    "Ear, Nose & Throat Hospitals",
    "Eating Disorder Clinics",
    "Electronic Medical Records Systems",
    "Emergency Veterinary Services",
    "Endocrinologists",
    "Endodontists",
    "Endoscope Manufacturing",
    "Energy Drink Production",
    "Environmental Testing",
    "Epilepsy Medication Manufacturing",
    "Erectile Dysfunction Medicine Manufacturing",
    "Eye Health Product Manufacturing OTC",
    "Eye Surgery Clinics",
    "Farm Animal Feed Production",
    "Fertility Clinics",
    "Foot Care Product Manufacturing",
    "Forensic Technology Services",
    "Geneticists",
    "Gerontologists",
    "Glucose Meter Manufacturing",
    "Gynecologists & Obstetricians",
    "Hair Loss Treatment Manufacturing",
    "Health & Wellness Spas",
    "Healthcare Staff Recruitment Agencies",
    "Hearing Aid Clinics",
    "Hearing Aid Manufacturing",
    "Hearing Protection Equipment Manufacturing",
    "Hepatologists",
    "Herbal Tea Production",
    "Homeopathic Medicine Manufacturing",
    "Homeopaths",
    "Hospices & Palliative Care Centers",
    "Hospital Bed Manufacturing",
    "Human Biologics Manufacturing",
    "Hydroponic Crop Farming",
    "Hypertension Drug Manufacturing",
    "Immunodermatologists",
    "Indigestion Medicine Manufacturing OTC",
    "Industrial Hemp Production",
    "Infectious Disease Specialists",
    "Insect Repellent Manufacturing",
    "Institutional Pharmacies",
    "Insulin Manufacturing",
    "Intravenous (IV) Hydration Centers",
    "Intravenous (IV) Solution Manufacturing",
    "Laboratory Casework Manufacturing",
    "Laboratory Fume Hoods Manufacturing",
    "Laboratory Glassware Manufacturing",
    "Laboratory Information Management Systems",
    "Life Coaches",
    "Luggage & Leather Goods Repair Shops",
    "Mammography Machine Manufacturing",
    "Mammography Services",
    "Marriage Counselors",
    "Medical & Recreational Marijuana Growing",
    "Medical & Recreational Marijuana Stores",
    "Medical Adhesives & Sealants Manufacturing",
    "Medical Case Management Services",
    "Medical Device Cleaning & Recycling",
    "Medical Equipment Repair & Maintenance Services",
    "Medical Marijuana Dispensaries",
    "Medical Transcription Services",
    "Medical Waste Disposal Services",
    "Memory Care Providers",
    "Midwives & Doulas",
    "Mobility Equipment Stores",
    "Natural Food Coloring Manufacturing",
    "Nebulizer Manufacturing",
    "Neonatal Physicians",
    "Nephrologists",
    "Neurologists",
    "Neuropathologists",
    "Neurotologists",
    "Nurse Practitioners",
    "Nutritionists & Dietitians",
    "Obesity Medication Manufacturing",
    "Occupational Health & Workplace Safety Services",
    "Occupational Therapists",
    "Oncologists",
    "Onshore Aquaculture",
    "Open Ocean Aquaculture",
    "Ophthalmic Equipment Dealers",
    "Ophthalmic Instrument Manufacturing",
    "Ophthalmologists",
    "Organ & Tissue Donor Services",
    "Organic Crop Farming",
    "Orthodontists",
    "Orthopedic Products Manufacturing",
    "Orthopedists",
    "Orthotic Manufacturing",
    "Otologists",
    "Pacemaker Manufacturing",
    "Pain Management Physicians",
    "Pain Medication Manufacturing OTC",
    "Pathologists",
    "Pediatric Dentists",
    "Pediatricians",
    "Periodontists",
    "Personal Trainers",
    "Pet Funeral & Cremation Services",
    "PET Scanner Manufacturing",
    "Pharmaceuticals Wholesaling",
    "Pharmacy Benefit Management",
    "Phlebologists",
    "Physical Therapy Rehabilitation Centers",
    "Physician Referral Services",
    "Pilates & Yoga Studios",
    "Plastic Surgeons",
    "Pneumonia Medication Manufacturing",
    "Prescription Acne Treatment Manufacturing",
    "Proctologists",
    "Prosthetics Manufacturing",
    "Protective Eyewear Manufacturing",
    "Psoriasis Medication Manufacturing",
    "Psychiatrists",
    "Pulmonologists",
    "Qi Gong & Tai Chi Studios",
    "Radiologists",
    "Relaxation Drink Production",
    "Respiratory Ventilator Manufacturing",
    "Retina Specialists",
    "Rheumatoid Arthritis Medication Manufacturing",
    "Rheumatologists",
    "Robotic Surgery Equipment Manufacturing",
    "Sex Therapists",
    "Sleep Aid Medication Manufacturing",
    "Sleep Disorder Clinics",
    "Speech-Language Pathologists",
    "Sports Medicine Practitioners",
    "Stent Manufacturing",
    "Surgical Apparel Manufacturing",
    "Surgical Instrument Manufacturing",
    "Syringes & Injection Needle Manufacturing",
    "Taekwondo Studios",
    "Teaching Hospitals",
    "Teeth Whitening Services",
    "Telehealth Services",
    "Thermometer Manufacturing",
    "Toxicology Laboratories",
    "Urgent Care Centers",
    "Urologists",
    "Venous Access Device Manufacturing",
    "Veterinary Laboratory Testing Services",
    "Weight Loss Surgery Centers",
    "Wheelchair Manufacturing",
    "Wildlife Rescue & Rehabilitation",
    "Wound Care Product Manufacturing",
    "X-Ray Machine Manufacturing",
    "Yeast & Bacteria for Food Production in the US"
  ],

  'Accommodation and Food Services': [
    "Accommodation and Food Services in the US",
    "Bars & Nightclubs in the US",
    "Bed & Breakfast & Hostel Accommodations in the US",
    "Campgrounds & RV Parks in the US",
    "Casino Hotels in the US",
    "Caterers in the US",
    "Chain Restaurants in the US",
    "Coffee & Snack Shops in the US",
    "Fast Food Restaurants in the US",
    "Food Service Contractors in the US",
    "Hotels & Motels in the US",
    "Single Location Full-Service Restaurants in the US",
    "Street Vendors in the US",
    "Tourism in the US"
  ],
  'Administration, Business Support and Waste Management Services':[
    "Business Service Centers in the US",
    "Carpet Cleaning in the US",
    "Convention & Visitor Bureaus in the US",
    "Correctional Facilities in the US",
    "Credit Bureaus & Rating Agencies in the US",
    "Debt Collection Agencies in the US",
    "Document Preparation Services in the US",
    "Employment & Recruiting Agencies in the US",
    "Human Resources & Benefits Administration in the US",
    "Janitorial Services in the US",
    "Landscaping Services in the US",
    "Office Staffing & Temp Agencies in the US",
    "Packaging & Labeling Services in the US",
    "Pest Control in the US",
    "Portable Toilet Rental & Septic Tank Cleaning in the US",
    "Professional Employer Organizations in the US",
    "Recycling Facilities in the US",
    "Remediation & Environmental Cleanup Services in the US",
    "Security Alarm Services in the US",
    "Security Services in the US",
    "Telemarketing & Call Centers in the US",
    "Tour Operators in the US",
    "Trade Show and Conference Planning in the US",
    "Travel Agencies in the US",
    "Waste Collection Services in the US",
    "Waste Treatment & Disposal Services in the US"],

  'Educational Services': [
    "Business Certification & IT Schools in the US",
    "Business Coaching in the US",
    "Colleges & Universities in the US",
    "Community Colleges in the US",
    "Educational Services in the US",
    "Fine Arts Schools in the US",
    "ForProfit Universities in the US",
    "Language Instruction in the US",
    "Private Schools in the US",
    "Public Schools in the US",
    "Sports Coaching in the US",
    "Testing & Educational Support in the US",
    "Trade & Technical Schools in the US",
    "Tutoring & Driving Schools in the US"],

  'Arts, Entertainment and Recreation': [
    "Arcade, Food & Entertainment Complexes in the US",
    "Arts, Entertainment and Recreation in the US",
    "Bowling Centers in the US",
    "Celebrity & Sports Agents in the US",
    "Concert & Event Promotion in the US",
    "Golf Courses & Country Clubs in the US",
    "Golf Driving Ranges & Family Fun Centers in the US",
    "Gym, Health & Fitness Clubs in the US",
    "Historic Sites in the US",
    "Lotteries & Native American Casinos in the US",
    "Marinas in the US",
    "Museums in the US",
    "Musical Groups & Artists in the US",
    "National Parks & Other Nature Institutions",
    "NonHotel Casinos in the US",
    "Performers & Creative Artists in the US",
    "Racing & Individual Sports in the US",
    "Ski & Snowboard Resorts in the US",
    "Sports Franchises in the USA"],

  'Wholesale Trade': [
    "Aircraft, Marine & Railroad Transportation Equipment Wholesaling in the US",
    "Auto Parts Wholesaling in the US",
    "Automobile Wholesaling in the US",
    "Beef & Pork Wholesaling in the US",
    "Beer Wholesaling in the US",
    "Book, Magazine & Newspaper Wholesaling in the US",
    "Camera & Film Wholesaling in the US",
    "Cattle & Hog Wholesaling in the US",
    "Chemical Wholesaling in the US",
    "Cigarette & Tobacco Products Wholesaling in the US",
    "Coal & Ore Wholesaling in the US",
    "Computer & Packaged Software Wholesaling in the US",
    "Confectionery Wholesaling in the US",
    "Construction & Mining Equipment Wholesaling in the US",
    "Copier & Office Equipment Wholesaling in the US",
    "Corn, Wheat & Soybean Wholesaling in the US",
    "Dairy Wholesaling in the US",
    "Drug, Cosmetic & Toiletry Wholesaling in the US",
    "Egg & Poultry Wholesaling in the US",
    "Electrical Equipment Wholesaling in the US",
    "Electronic Part & Equipment Wholesaling in the US",
    "Farm Supplies Wholesaling in the US",
    "Farm, Lawn & Garden Equipment Wholesaling in the US",
    "Fish & Seafood Wholesaling in the US",
    "Flower & Nursery Stock Wholesaling in the US",
    "Footwear Wholesaling in the US",
    "Frozen Food Wholesaling in the US",
    "Fruit & Vegetable Wholesaling in the US",
    "Furniture Wholesaling in the US",
    "Gasoline & Petroleum Bulk Stations in the US",
    "Gasoline & Petroleum Wholesaling in the US",
    "Glasses & Contacts Wholesaling in the US",
    "Grocery Wholesaling in the US",
    "Heating & Air Conditioning Wholesaling in the US",
    "Home Furnishing Wholesaling in the US",
    "Industrial Machinery & Equipment Wholesaling in the US",
    "Industrial Supplies Wholesaling in the US",
    "Janitorial Equipment Supply Wholesaling in the US",
    "Jewelry & Watch Wholesaling in the US",
    "Laboratory Supply Wholesaling in the US",
    "Lumber Wholesaling in the US",
    "Manufactured Home Wholesaling in the US",
    "Medical Supplies Wholesaling in the US",
    "Men's & Boys' Apparel Wholesaling in the US",
    "Metal Wholesaling in the US",
    "Office Stationery Wholesaling in the US",
    "Paint Wholesaling in the US",
    "Paper Bag & Disposable Plastic Product Wholesaling in the US",
    "Paper Wholesaling in the US",
    "Piece Goods, Notions & Other Apparel Wholesaling in the US",
    "Plastics Wholesaling in the US",
    "Plumbing & Heating Supplies Wholesaling in the US",
    "Recyclable Material Wholesaling in the US",
    "Refrigeration Equipment Wholesaling in the US",
    "Restaurant & Hotel Equipment Wholesaling in the US",
    "Roofing, Siding & Insulation Wholesaling in the US",
    "Soft Drink, Baked Goods & Other Grocery Wholesaling in the US",
    "Sporting Goods Wholesaling in the US",
    "Stone, Concrete & Clay Wholesaling in the US",
    "Tire Wholesaling in the US",
    "Tool & Hardware Wholesaling in the US",
    "Toy & Craft Supplies Wholesaling in the US",
    "TV & Appliance Wholesaling in the US",
    "Used Car Parts Wholesaling in the US",
    "Wholesale Trade Agents and Brokers",
    "Wholesale Trade in the US",
    "Wine & Spirits Wholesaling in the US",
    "Women's & Children's Apparel",
    "Wholesaling in the US"],

  'Retail Trade':[
    "Art Dealers in the US",
    "Auto Parts Stores in the US",
    "Beauty, Cosmetics & Fragrance Stores in the US",
    "Beer, Wine & Liquor Stores in the US",
    "Bicycle Dealership and Repair in the US",
    "Boat Dealership and Repair in the US",
    "Book Stores in the US",
    "Camera Stores in the US",
    "Children's & Infants' Clothing Stores in the US",
    "Computer Stores in the US",
    "Consumer Electronics Stores in the US",
    "Convenience Stores in the US",
    "Department Stores in the US",
    "Direct Selling Companies in the US",
    "Dollar & Variety Stores in the US",
    "ECommerce & Online Auctions in the US",
    "Eyeglasses & Contact Lens Stores in the US",
    "Fabric, Craft & Sewing Supplies Stores in the US",
    "Family Clothing Stores in the US",
    "Fish & Seafood Markets in the US",
    "Floor Covering Stores in the US",
    "Florists in the US",
    "Fruit & Vegetable Markets in the US",
    "Fuel Dealers in the US",
    "Furniture Stores in the US",
    "Gas Stations in the US",
    "Gas Stations with Convenience Stores in the US",
    "Gift Shops & Card Stores in the US",
    "Handbag, Luggage & Accessory Stores in the US",
    "Hardware Stores in the US",
    "Health Stores in the US",
    "Hobby & Toy Stores in the US",
    "Home Furnishings Stores in the US",
    "Home Improvement Stores in the US",
    "Jewelry Stores in the US",
    "Lawn & Outdoor Equipment Stores in the US",
    "Lingerie, Swimwear & Bridal Stores in the US",
    "Lumber & Building Material Stores in the US",
    "Mail Order in the US",
    "Manufactured Home Dealers in the US",
    "Meat Markets in the US",
    "Men's Clothing Stores in the US",
    "Motorcycle Dealership and Repair in the US",
    "Musical Instrument & Supplies Stores in the US",
    "New Car Dealers in the US",
    "Nursery & Garden Stores in the US",
    "Office Supply Stores in the US",
    "Paint Stores in the US",
    "Pet Stores in the US",
    "Pharmacies & Drug Stores in the US",
    "Record Stores in the US",
    "Recreational Vehicle Dealers in the US",
    "Retail Trade in the US",
    "Shoe Stores in the US",
    "Small Specialty Retail Stores in the US",
    "Specialty Food Stores in the US",
    "Sporting Goods Stores in the US",
    "Supermarkets & Grocery Stores in the US",
    "Tire Dealers in the US",
    "Used Car Dealers in the US",
    "Used Goods Stores in the US",
    "Vending Machine Operators in the US",
    "Warehouse Clubs & Supercenters in the US",
    "Women's Clothing Stores in the US"],

  'Healthcare and Social Assistance':[
    "Adoption & Child Welfare Services in the US",
    "Alternative Healthcare Providers in the US",
    "Ambulance Services in the US",
    "Biotechnology in the US",
    "Blood & Organ Banks in the US",
    "Chiropractors in the US",
    "Community Food Services in the US",
    "Community Housing & Homeless Shelters in the US",
    "Day Care in the US",
    "Dentists in the US",
    "Diagnostic & Medical Laboratories in the US",
    "Elderly & Disabled Services in the US",
    "Emergency & Other Outpatient Care Centers in the US",
    "Family Counseling & Crisis Intervention Services in the US",
    "Family Planning & Abortion Clinics in the US",
    "Healthcare and Social Assistance in the US",
    "Home Care Providers in the US",
    "Hospitals in the US",
    "Job Training & Career Counseling in the US",
    "Mental Health & Substance Abuse Centers in the US",
    "Mental Health & Substance Abuse Clinics in the US",
    "Natural Disaster & Emergency Relief Services in the US",
    "Nursing Care Facilities in the US",
    "Optometrists in the US",
    "Orphanages & Group Homes in the US",
    "Physical Therapists in the US",
    "Podiatrists in the US",
    "Primary Care Doctors in the US",
    "Psychiatric Hospitals in the US",
    "Psychologists, Social Workers & Marriage Counselors in the US",
    "Residential Intellectual Disability Facilities in the US",
    "Retirement Communities in the US",
    "Specialist Doctors in the US",
    "Specialty Hospitals in the US"],
  
  'Transportation and Warehousing': [
    "Aircraft Maintenance, Repair & Overhaul in the US",
    "Airport Operations in the US",
    "Automobile Towing in the US",
    "Charter Flights in the US",
    "Couriers & Local Delivery Services in the US",
    "Domestic Airlines in the US",
    "Dry Docks & Cargo Inspection Services in the US",
    "Farm Product Storage & Warehousing in the US",
    "Freight Forwarding Brokerages & Agencies in the US",
    "Freight Packing & Logistics Services in the US",
    "Gas Pipeline Transportation in the US",
    "Inland Water Transportation in the US",
    "International Airlines in the US",
    "Local Freight Trucking in the US",
    "Local Specialized Freight Trucking in the US",
    "Long-Distance Freight Trucking in the US",
    "Moving Services in the US",
    "Ocean & Coastal Transportation in the US",
    "Oil Pipeline Transportation in the US",
    "Organic Chemical Pipeline Transportation in the US",
    "Port & Harbor Operations in the US",
    "Postal Service in the US",
    "Public School Bus Services in the US",
    "Public Storage & Warehousing in the US",
    "Public Transportation in the US",
    "Rail Maintenance Services in the US",
    "Rail Transportation in the US",
    "Refined Petroleum Pipeline Transportation in the US",
    "Refrigerated Storage in the US",
    "Scheduled and Charter Bus Services in the US",
    "Sightseeing Transportation in the US",
    "Specialized Storage & Warehousing in the US",
    "Stevedoring & Marine Cargo Handling in the US",
    "Tank & Refrigeration Trucking in the US",
    "Taxi & Limousine Services in the US",
    "Toll Roads & Weigh Stations in the US",
    "Transportation and Warehousing in the US",
    "Tugboat & Shipping Navigational Services in the US"],

  'Construction': [
    "Apartment & Condominium Construction in the US",
    "Bridge & Elevated Highway Construction in the US",
    "Building Finishing Contractors in the US",
    "Carpenters in the US",
    "Commercial Building Construction in the US",
    "Concrete Contractors in the US",
    "Construction in the US",
    "Demolition & Wrecking in the US",
    "Drywall & Insulation Installers in the US",
    "Electricians in the US",
    "Elevator Installation & Service in the US",
    "Excavation Contractors in the US",
    "Fence Construction in the US",
    "Flooring Installers in the US",
    "Glass & Glazing Contractors in the US",
    "Heating & Air Conditioning Contractors in the US",
    "Heavy Engineering Construction in the US",
    "Home Builders in the US",
    "Housing Developers in the US",
    "Industrial Building Construction in the US",
    "Land Development in the US",
    "Masonry in the US",
    "Municipal Building Construction in the US",
    "Oil & Gas Pipeline Construction in the US",
    "Painters in the US",
    "Paving Contractors in the US",
    "Plumbers in the US",
    "Remodeling in the US",
    "Road & Highway Construction in the US",
    "Roofing Contractors in the US",
    "Steel Framing in the US",
    "Sustainable Building Material Manufacturing in the US",
    "Swimming Pool Construction in the US",
    "Tile Installers in the US",
    "Transmission Line Construction in the US",
    "Water & Sewer Line Construction in the US",
    "Wood Framing in the US"],

  'Professional, Scientific and Technical Services':[
    "Accounting Services in the US",
    "Advertising Agencies in the US",
    "Architects in the US",
    "Billboard & Outdoor Advertising in the US",
    "Building Inspectors in the US",
    "Conveyancing Services in the US",
    "Credit Counselors, Surveyors & Appraisers in the US",
    "Direct Mail Advertising in the US",
    "Engineering Services in the US",
    "Environmental Consulting in the US",
    "Fashion Designers in the US",
    "Geophysical Services in the US",
    "Graphic Designers in the US",
    "HR Consulting in the US",
    "Industrial Designers in the US",
    "Interior Designers in the US",
    "IT Consulting in the US",
    "Laboratory Testing Services in the US",
    "Landscape Design in the US",
    "Law Firms in the US",
    "Management Consulting in the US",
    "Market Research in the US",
    "Media Buying Agencies in the US",
    "Media Representative Firms in the US",
    "Payroll & Bookkeeping Services in the US",
    "Photography in the US",
    "Print Advertising Distribution in the US",
    "Professional, Scientific and Technical Services in the US",
    "Promotional Products in the US",
    "Public Relations Firms in the US",
    "Scientific & Economic Consulting in the US",
    "Scientific Research & Development in the US",
    "Surveying & Mapping Services in the US",
    "Tax Preparation Services in the US",
    "Translation Services in the US",
    "Veterinary Services in the US"],

  'Manufacturing': [
    "Abrasive & Sandpaper Manufacturing in the US",
    "Adhesive Manufacturing in the US",
    "Aircraft, Engine & Parts Manufacturing in the US",
    "Alarm, Horn & Traffic Control Equipment Manufacturing in the US",
    "Aluminum Manufacturing in the US",
    "Animal Food Production in the US",
    "Apparel Knitting Mills in the US",
    "Art & Office Supply Manufacturing in the US",
    "Asphalt Manufacturing in the US",
    "Athletic & Sporting Goods Manufacturing in the US",
    "ATV, Golf Cart & Snowmobile Manufacturing in the US",
    "Audio & Video Equipment Manufacturing in the US",
    "Auto Parts Manufacturing in the US",
    "Automobile Brakes Manufacturing in the US",
    "Automobile Electronics Manufacturing in the US",
    "Automobile Engine & Parts Manufacturing in the US",
    "Automobile Interior Manufacturing in the US",
    "Automobile Metal Stamping in the US",
    "Automobile Steering & Suspension Manufacturing in the US",
    "Automobile Transmission Manufacturing in the US",
    "Baking Mix & Prepared Food Production in the US",
    "Ball Bearing Manufacturing in the US",
    "Battery Manufacturing in the US",
    "Billboard & Sign Manufacturing in the US",
    "Blind & Shade Manufacturing in the US",
    "Boat Building in the US",
    "Boiler & Heat Exchanger Manufacturing in the US",
    "Bottled Water Production in the US",
    "Brand Name Pharmaceutical Manufacturing in the US",
    "Bread Production in the US",
    "Breweries in the US",
    "Cabinet & Vanity Manufacturing in the US",
    "Candy Production in the US",
    "Canned Fruit & Vegetable Processing in the US",
    "Car & Automobile Manufacturing in the US",
    "Cardboard Box & Container Manufacturing in the US",
    "Carpet Mills in the US",
    "Cement Manufacturing in the US",
    "Ceramics Manufacturing in the US",
    "Cereal Production in the US",
    "Chemical Product Manufacturing in the US",
    "Chocolate Production in the US",
    "Cigarette & Tobacco Manufacturing in the US",
    "Circuit Board & Electronic Component Manufacturing in the US",
    "Clay Brick & Product Manufacturing in the US",
    "Coated & Laminated Paper Manufacturing in the US",
    "Coffee Production in the US",
    "Communication Equipment Manufacturing in the US",
    "Computer Manufacturing in the US",
    "Computer Peripheral Manufacturing in the US",
    "Concrete Pipe & Block Manufacturing in the US",
    "Construction Machinery Manufacturing in the US",
    "Cookie, Cracker & Pasta Production in the US",
    "Copier & Optical Machinery Manufacturing in the US",
    "Copper Rolling, Drawing & Extruding in the US",
    "Cosmetic & Beauty Products Manufacturing in the US",
    "Costume & Team Uniform Manufacturing in the US",
    "Cut and Sew Manufacturers in the US",
    "Dairy Product Production in the US",
    "Distilleries in the US",
    "Dye & Pigment Manufacturing in the US",
    "Electrical Equipment Manufacturing in the US",
    "Engine & Turbine Manufacturing in the US",
    "Explosives Manufacturing in the US",
    "Ferrous Metal Foundry Products in the US",
    "Fertilizer Manufacturing in the US",
    "Flour Milling in the US",
    "Forklift & Conveyor Manufacturing in the US",
    "Frozen Food Production in the US",
    "Generic Pharmaceutical Manufacturing in the US",
    "Glass Product Manufacturing in the US",
    "Glasses & Contact Lens Manufacturing in the US",
    "Guns & Ammunition Manufacturing in the US",
    "Gym & Exercise Equipment Manufacturing in the US",
    "Gypsum Product Manufacturing in the US",
    "Hand Tool & Cutlery Manufacturing in the US",
    "Hardware Manufacturing in the US",
    "Heating & Air Conditioning Equipment Manufacturing in the US",
    "Hose & Belt Manufacturing in the US",
    "Hosiery Mills in the US",
    "Household Furniture Manufacturing in the US",
    "Ice Cream Production in the US",
    "Ink Manufacturing in the US",
    "Inorganic Chemical Manufacturing in the US",
    "Iron & Steel Manufacturing in the US",
    "Jewelry Manufacturing in the US",
    "Juice Production in the US",
    "Laminated Plastics Manufacturing in the US",
    "Leather Good & Luggage Manufacturing in the US",
    "Leather Tanning & Finishing in the US",
    "Lighting & Bulb Manufacturing in the US",
    "Lighting Fixtures Manufacturing in the US",
    "Lime Manufacturing in the US",
    "Lubricant Oil Manufacturing in the US",
    "Machine Shop Services in the US",
    "Major Household Appliance Manufacturing in the US",
    "Manufacturing in the US",
    "Margarine & Cooking Oil Processing in the US",
    "Mattress Manufacturing in the US",
    "Meat, Beef & Poultry Processing in the US",
    "Medical Device Manufacturing in the US",
    "Medical Instrument & Supply Manufacturing in the US",
    "Men's & Boys' Apparel Manufacturing in the US",
    "Metal Can & Container Manufacturing in the US",
    "Metal Pipe & Tube Manufacturing in the US",
    "Metal Plating & Treating in the US",
    "Metal Stamping & Forging in the US",
    "Metal Tank Manufacturing in the US",
    "Metalworking Machinery Manufacturing in the US",
    "Millwork in the US",
    "Mineral Product Manufacturing in the US",
    "Mining, Oil & Gas Machinery Manufacturing in the US",
    "Motorcycle, Bike & Parts Manufacturing in the US",
    "Navigational Instrument Manufacturing in the US",
    "Nonferrous Metal Foundry Products Manufacturing in the US",
    "Nonferrous Metal Refining in the US",
    "Nonferrous Metal Rolling & Alloying in the US",
    "Office Furniture Manufacturing in the US",
    "Office Stationery Manufacturing in the US",
    "Organic Chemical Manufacturing in the US",
    "Oxygen & Hydrogen Gas Manufacturing in the US",
    "Paint Manufacturing in the US",
    "Paper Mills in the US",
    "Paper Product Manufacturing in the US",
    "Paperboard Mills in the US",
    "Pesticide Manufacturing in the US",
    "Petrochemical Manufacturing in the US",
    "Petroleum Refining in the US",
    "Plastic & Resin Manufacturing in the US",
    "Plastic Bottle Manufacturing in the US",
    "Plastic Film, Sheet & Bag Manufacturing in the US",
    "Plastic Pipe & Parts Manufacturing in the US",
    "Plastic Products Miscellaneous Manufacturing in the US",
    "Plastics & Rubber Machinery Manufacturing in the US",
    "Polystyrene Foam Manufacturing in the US",
    "Power Conversion Equipment Manufacturing in the US",
    "Power Tools & Other General Purpose Machinery Manufacturing in the US",
    "Precast Concrete Manufacturing in the US",
    "Prefabricated Home Manufacturing in the US",
    "Printing in the US",
    "Printing Services in the US",
    "Printing, Paper, Food, Textile & Other Machinery Manufacturing in the US",
    "Pump & Compressor Manufacturing in the US",
    "Quick Printing in the US",
    "ReadyMix Concrete Manufacturing in the US",
    "Recordable Media Manufacturing in the US",
    "Rubber Product Manufacturing in the US",
    "Sanitary Paper Product Manufacturing in the US",
    "Sawmills & Wood Production in the US",
    "Screw, Nut & Bolt Manufacturing in the US",
    "Seafood Preparation in the US",
    "Seasoning, Sauce and Condiment Production in the US",
    "Semiconductor & Circuit Manufacturing in the US",
    "Semiconductor Machinery Manufacturing in the US",
    "Sheet Metal, Window & Door Manufacturing in the US",
    "Ship Building in the US",
    "Shoe & Footwear Manufacturing in the US",
    "Snack Food Production in the US",
    "Soap & Cleaning Compound Manufacturing in the US",
    "Soda Production in the US",
    "Solar Panel Manufacturing in the US",
    "Space Vehicle & Missile Manufacturing in the US",
    "Steel Rolling & Drawing in the US",
    "Structural Metal Product Manufacturing in the US",
    "Sugar Processing in the US",
    "SUV & Light Truck Manufacturing in the US",
    "Synthetic Fiber Manufacturing in the US",
    "Syrup & Flavoring Production in the US",
    "Tank & Armored Vehicle Manufacturing in the US",
    "Tea Production in the US",
    "Telecommunication Networking Equipment Manufacturing in the US",
    "Textile Mills in the US",
    "Tire Manufacturing in the US",
    "Tortilla Production in the US",
    "Toy, Doll & Game Manufacturing in the US",
    "Tractors & Agricultural Machinery Manufacturing in the US",
    "Train, Subway & Transit Car Manufacturing in the US",
    "Truck & Bus Manufacturing in the US",
    "Truck, Trailer & Motor Home Manufacturing in the US",
    "Urethane Foam Manufacturing in the US",
    "Vacuum, Fan & Small Household Appliance Manufacturing in the US",
    "Valve Manufacturing in the US",
    "Vitamin & Supplement Manufacturing in the US",
    "Wind Turbine Manufacturing in the US",
    "Wineries in the US",
    "Wire & Cable Manufacturing in the US",
    "Wire & Spring Manufacturing in the US",
    "Wiring Device Manufacturing in the US",
    "Womens', Girls' and Infants' Apparel Manufacturing in the US",
    "Wood Pallets & Skids Production in the US",
    "Wood Paneling Manufacturing in the US",
    "Wood Product Manufacturing in the US",
    "Wood Pulp Mills in the US",
    "Woodworking Machinery Manufacturing in the US"
  ],


  }

  export interface IService {
    category: string;
    items: string[];
  }
  
  export interface IServiceList {
    services: IService[];
  }
  
  export interface Props {
    answer1: string;
  }